name: Build flashable kernel

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source Code
      uses: actions/checkout@v3
      with:
        github-server-url: 'https://github.com'
        repository: zeroXone-two/android_kernel_xiaomi_sm8350
        ref: 14-built-in
        path: kernel-srcroot
   
    - name: Setup Kernel SU
      run: |
        cd kernel-srcroot
        rm -rf KernelSU
        git config --global user.email "you@example.com"
        git config --global user.name "zeroXone-github"
        git add .
        git commit -m "Blump up KSU for NonGKI kernel"
        git submodule init
        git submodule update --checkout
        git push origin
